name: 'action-test-one action'
description: 'This is the first action that we are going to call'
runs:
  using: "composite"
  steps:
    - name: First step of action-test-one
      shell: bash
      run: |
        echo "This is an output of the FIRST step of the action-test-one"
        export STEP_OUTPUT
        $STEP_OUTPUT="{test}"
        echo $STEP_OUTPUT
        echo "set-output::test-var::$STEP_OUTPUT"
    - name: Second step of action-test-one
      shell: bash
      run: |
        echo "This is an output of the SECOND step of the action-test-one"
