name: 'action-test-two action'
description: 'This is the second action that we are going to call'
runs:
  using: "composite"
  steps:
    - name: First step of action-test-one
      run: |
        echo "This is an output of the FIRST step of the action-test-two"
    - name: Second step of action-test-one
      run: |
        echo "This is an output of the SECOND step of the action-test-two"
